### ISSUE TITLE
Override the download button functionality and expose other tool bar options

### ISSUE THREAD

**Issue by pg2203** [legalthings/angular-pdfjs-viewer#25] opened 2016-12-20 22:10 UTC
angular-pdfjs-viewer is great library, can we expose all other tool bar options so as to show or hide some of them. Another requirement i came across is to override the download button functionality, i got into situation where on download should make server call to retrieve raw document( which is in other format like .docx or .pptx etc..). I am converting into PDF and passing to pdfjs-viewer to view in the webpage.

**Comment by jasny** [comment] 2016-12-22 03:32
Duplicate of #23. You can by using a decorator.

Overwriting the functionality of a button might be possible by listing to the click event of the button. The plugin isn't able to do something like that out of the box though.

**Closed as completed by jasny** 2016-12-22 03:32 UTC
