### ISSUE TITLE
PDFJS.webViewerLoad is not a function

### ISSUE THREAD

**Issue by mowaiskalam** [legalthings/angular-pdfjs-viewer#43] opened 2017-05-14 18:09 UTC
I have include PDF.js and also set the url of pdf.worker.js but still i am getting this error in console. What i am doing wrong ?

**Comment by mowaiskalam** [comment] 2017-05-17 19:44
@jasny @KillaBee1985 @pranjal-goswami @subdee @sven4ask is anybody here to address this issue ?

**Comment by jasny** [comment] 2017-05-18 13:07
This ticket is a duplicate of https://github.com/legalthings/angular-pdfjs-viewer/issues/38

**Closed as completed by jasny** 2017-05-18 13:07 UTC
